name: Build and Release Extension

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Extension
        run: npm run build

      - name: Zip Build Output
        run: |
          cd dist
          zip -r ../clip-bookmark-${{ github.event.release.tag_name }}.zip *
          cd ..

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./clip-bookmark-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
